// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menuLink': string;
  'menuLinkSelected': string;
  'menuList': string;
  'rootContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
