// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'courseDescriptionBlock': string;
  'coursePreviewVideoBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
