// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'content': string;
  'input': string;
  'submitBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
