// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'container': string;
  'part': string;
  'part1': string;
  'part2': string;
  'part3': string;
}
export const cssExports: CssExports;
export default cssExports;
