// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomBlock': string;
  'copyright': string;
  'footer': string;
  'footerConent': string;
  'list': string;
  'sectionFour': string;
  'sectionOne': string;
  'sectionThree': string;
  'sectionTwo': string;
  'topBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
