// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'size-2xl': string;
  'size-3xl': string;
  'size-4xl': string;
  'size-5xl': string;
  'size-l': string;
  'size-m': string;
  'size-s': string;
  'size-xl': string;
  'size-xs': string;
}
export const cssExports: CssExports;
export default cssExports;
