// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'heading': string;
  'iframe': string;
  'img1': string;
  'img2': string;
  'img3': string;
  'paragraph': string;
  'textBlock': string;
  'textWrapper': string;
  'videoBlock': string;
  'videoWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
