// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bgFormImg': string;
  'container': string;
  'dotsImg': string;
  'girlImg': string;
  'heading': string;
  'iframe': string;
  'paragraph': string;
  'textBlock': string;
  'textWrapper': string;
  'videoBlock': string;
  'videoWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
