// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'body': string;
  'button': string;
  'buttonBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
