// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'image': string;
  'imageWrapper': string;
  'mainPlusesBlock': string;
  'plusesBlock': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
