// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'definition': string;
  'left': string;
  'paragraph': string;
  'right': string;
}
export const cssExports: CssExports;
export default cssExports;
