// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'body': string;
  'header': string;
  'info': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
