// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'hiddenPart': string;
  'icon': string;
  'innerContainer': string;
  'text': string;
  'visiblePart': string;
}
export const cssExports: CssExports;
export default cssExports;
