// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'loginForm': string;
  'loginPage': string;
  'loginSwitchButton': string;
}
export const cssExports: CssExports;
export default cssExports;
