// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'paddingsOnPhone': string;
  'pageContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
