// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heading': string;
  'image': string;
  'infoBlock': string;
  'link': string;
  'mainScreenBlock': string;
  'subheader': string;
  'subtext': string;
  'subtextContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
