// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'contentBlock': string;
  'description': string;
  'image': string;
  'imageContainer': string;
  'leftDirection': string;
  'rightDirection': string;
  'subtitle': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
