// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'completeIcon': string;
  'continueLink': string;
  'progressCount': string;
}
export const cssExports: CssExports;
export default cssExports;
