// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'content': string;
  'desc': string;
  'disabled': string;
  'picture': string;
  'playIcon': string;
  'root': string;
  'time': string;
  'timeCounter': string;
  'timeIcon': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
