// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blogBlock': string;
  'bottomContent': string;
  'bottomContentLeft': string;
  'bottomContentRight': string;
  'header': string;
}
export const cssExports: CssExports;
export default cssExports;
