// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'extra': string;
  'image': string;
  'info': string;
  'name': string;
  'userLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
