// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'body': string;
  'card': string;
  'header': string;
  'heading': string;
  'image': string;
  'text': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
