// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'button': string;
  'control': string;
  'description': string;
  'subtitle': string;
  'target': string;
}
export const cssExports: CssExports;
export default cssExports;
