// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'button': string;
  'clockIcon': string;
  'column': string;
  'control': string;
  'counter': string;
  'description': string;
  'imageTitleWrapper': string;
  'jsIcon': string;
  'jsImage': string;
  'paragraph': string;
  'resourceImage': string;
  'row': string;
  'subtitle': string;
  'target': string;
  'time': string;
  'title': string;
  'video': string;
  'videosWrapper': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
