// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'counter': string;
  'course': string;
  'courseTitle': string;
  'gray': string;
  'header': string;
  'icons': string;
  'image': string;
  'management': string;
  'title': string;
  'videoTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
