// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base': string;
  'burger': string;
  'logoMobile': string;
  'menu': string;
  'padding': string;
}
export const cssExports: CssExports;
export default cssExports;
