// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonLink': string;
  'container': string;
  'link': string;
  'loginIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
