// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonIcon': string;
  'buttonPrimary': string;
  'buttonSecondary': string;
}
export const cssExports: CssExports;
export default cssExports;
