// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'courseParagraph': string;
  'description': string;
  'playlistBlock': string;
  'textWrapper': string;
  'time': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
