// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'inputSimple': string;
  'label': string;
  'labelFilled': string;
}
export const cssExports: CssExports;
export default cssExports;
