// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'statBlock': string;
  'statDesc': string;
  'statItem': string;
}
export const cssExports: CssExports;
export default cssExports;
